ALTER TABLE public.api_keys
  ADD COLUMN IF NOT EXISTS limit_window TEXT NOT NULL DEFAULT 'infinite',
  ADD COLUMN IF NOT EXISTS limit_reset_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS token_limit BIGINT,
  ADD COLUMN IF NOT EXISTS current_token_spend BIGINT NOT NULL DEFAULT 0;